export const publicConfig = {
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'contact@deliivo.com',
  supportEmail: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'support@deliivo.com',
  legalEmail: process.env.NEXT_PUBLIC_LEGAL_EMAIL || 'legal@deliivo.com',
  privacyEmail: process.env.NEXT_PUBLIC_PRIVACY_EMAIL || 'privacy@deliivo.com',
  instagramUrl: process.env.NEXT_PUBLIC_INSTAGRAM_URL || 'https://www.instagram.com/deliivoapp',
  facebookUrl: process.env.NEXT_PUBLIC_FACEBOOK_URL || 'https://www.facebook.com/deliivoapp',
  xUrl: process.env.NEXT_PUBLIC_X_URL || 'https://x.com/Deliivoapp',
  tiktokUrl: process.env.NEXT_PUBLIC_TIKTOK_URL || 'https://www.tiktok.com/@deliivo.app',
  linkedinUrl: process.env.NEXT_PUBLIC_LINKEDIN_URL || 'https://www.linkedin.com/company/deliivo',
  siteUrl: (process.env.NEXT_PUBLIC_SITE_URL || 'https://deliivo-webapp.vercel.app').replace(/\/$/, ''),
  gaMeasurementId: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || 'G-MSG1B1Y353',
  googleSiteVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || 'SU-QN9TplRKM9Kn7lq1H07KiKc93qQZfRhMDveuw1H4',
  defaultOgImagePath: process.env.NEXT_PUBLIC_DEFAULT_OG_IMAGE_PATH || '/baltic-hero-v2.png',
};
