FROM node:20-alpine AS base

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source
COPY src ./src/
COPY public ./public/
COPY next.config.ts tsconfig.json ./
COPY postcss.config.mjs ./

ENV NEXT_TELEMETRY_DISABLED=1

# Build-time args for NEXT_PUBLIC_ vars (baked into client JS bundle)
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
ARG NEXT_PUBLIC_ALLOW_RIDE_SIMULATION=false
ARG NEXT_PUBLIC_ALLOW_RIDE_MANUAL_OVERRIDE=false
ARG NEXT_PUBLIC_PUBLISH_CITY_POINT_RADIUS_KM=15
ARG NEXT_PUBLIC_PUBLISH_STOPOVER_POINT_RADIUS_KM=5
ARG NEXT_PUBLIC_PUBLISH_ROUTE_POINT_RADIUS_KM=10
ARG NEXT_PUBLIC_SOCKET_URL=http://localhost:3000
ARG NEXT_PUBLIC_FIREBASE_API_KEY=
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
ARG NEXT_PUBLIC_FIREBASE_APP_ID=
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY=
ARG NEXT_PUBLIC_CONTACT_EMAIL=contact@deliivo.com
ARG NEXT_PUBLIC_SUPPORT_EMAIL=support@deliivo.com
ARG NEXT_PUBLIC_LEGAL_EMAIL=legal@deliivo.com
ARG NEXT_PUBLIC_PRIVACY_EMAIL=privacy@deliivo.com
ARG NEXT_PUBLIC_INSTAGRAM_URL=https://www.instagram.com/deliivoapp
ARG NEXT_PUBLIC_FACEBOOK_URL=https://www.facebook.com/deliivoapp
ARG NEXT_PUBLIC_X_URL=https://x.com/Deliivoapp
ARG NEXT_PUBLIC_TIKTOK_URL=https://www.tiktok.com/@deliivo.app
ARG NEXT_PUBLIC_LINKEDIN_URL=https://www.linkedin.com/company/deliivo
ARG NEXT_PUBLIC_SITE_URL=https://deliivo-webapp.vercel.app
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID=G-MSG1B1Y353
ARG NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=SU-QN9TplRKM9Kn7lq1H07KiKc93qQZfRhMDveuw1H4
ARG NEXT_PUBLIC_DEFAULT_OG_IMAGE_PATH=/baltic-hero-v2.png

ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_ALLOW_RIDE_SIMULATION=$NEXT_PUBLIC_ALLOW_RIDE_SIMULATION
ENV NEXT_PUBLIC_ALLOW_RIDE_MANUAL_OVERRIDE=$NEXT_PUBLIC_ALLOW_RIDE_MANUAL_OVERRIDE
ENV NEXT_PUBLIC_PUBLISH_CITY_POINT_RADIUS_KM=$NEXT_PUBLIC_PUBLISH_CITY_POINT_RADIUS_KM
ENV NEXT_PUBLIC_PUBLISH_STOPOVER_POINT_RADIUS_KM=$NEXT_PUBLIC_PUBLISH_STOPOVER_POINT_RADIUS_KM
ENV NEXT_PUBLIC_PUBLISH_ROUTE_POINT_RADIUS_KM=$NEXT_PUBLIC_PUBLISH_ROUTE_POINT_RADIUS_KM
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=$NEXT_PUBLIC_FIREBASE_VAPID_KEY
ENV NEXT_PUBLIC_CONTACT_EMAIL=$NEXT_PUBLIC_CONTACT_EMAIL
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_LEGAL_EMAIL=$NEXT_PUBLIC_LEGAL_EMAIL
ENV NEXT_PUBLIC_PRIVACY_EMAIL=$NEXT_PUBLIC_PRIVACY_EMAIL
ENV NEXT_PUBLIC_INSTAGRAM_URL=$NEXT_PUBLIC_INSTAGRAM_URL
ENV NEXT_PUBLIC_FACEBOOK_URL=$NEXT_PUBLIC_FACEBOOK_URL
ENV NEXT_PUBLIC_X_URL=$NEXT_PUBLIC_X_URL
ENV NEXT_PUBLIC_TIKTOK_URL=$NEXT_PUBLIC_TIKTOK_URL
ENV NEXT_PUBLIC_LINKEDIN_URL=$NEXT_PUBLIC_LINKEDIN_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=$NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
ENV NEXT_PUBLIC_DEFAULT_OG_IMAGE_PATH=$NEXT_PUBLIC_DEFAULT_OG_IMAGE_PATH

RUN npm run build

# Production image
FROM node:20-alpine AS production

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=base /app/package.json ./
COPY --from=base /app/node_modules ./node_modules/
COPY --from=base /app/.next ./.next/
COPY --from=base /app/public ./public/

EXPOSE 3001

ENV PORT=3001
CMD ["npx", "next", "start", "-p", "3001"]
